# Generated by Django 5.2.4 on 2025-07-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hmi',
            name='group',
        ),
        migrations.AddField(
            model_name='hmi',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='hmis', to='api.hmigroup'),
        ),
    ]
