# Generated by Django 5.2.4 on 2025-07-04 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_hmi_group_hmi_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmi',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hmis', to='api.organization'),
            preserve_default=False,
        ),
    ]
